database:
  hostname: localhost
  port: 3306
  username: root
  password: password
  database: AltitudeTag
  timeout: 100
  description: 'Altitude Connection'
leaderboard:
  enabled: true
  title: '&b&lAltitude Tag Leaderboard'
  format: '&6{rank}. &e{player} &7- &e{tags}'
  top: 10
  location:
    world: world
    x: 10.0
    y: 50.0
    z: 10.0
notification:
  victim:
    title:
      enabled: true
      message: '&6Tag'
      duration: 100
      fade-in: 0
      fade-out: 0
      sub-title:
        enabled: true
        message: "&eYou're it!"
      join-delay:
        enabled: true
        length: 60
  attacker:
    chat:
      enabled: true
      message: "&7You just tagged &e{target}&7! You have &e{amount}&7 total tags."
  global:
    chat:
      after-tag:
        enabled: true
        message: "&e* {attacker} tagged {target}, run!"
      other-reason:
        enabled: true
        message: "&e* {target} is now 'it'! Don't let them tag you!"
    boss-bar:
      enabled: true
      # Options: 0, 6, 10, 12, 20
      segments: 0
      # Blue, Green, Pink, Purple, Red, White, Yellow
      color: YELLOW
      # 0-100
      percent: 0
      message: "&e{player} is 'it'! Don't let them tag you!"